framework:
    #ide: 'phpstorm://open?url=file://%%f&line=%%l'
    #ide: 'phpstorm://open?file=%%f&line=%%l&/var/www/html/>C:/Webservers/home/symfony5/'
    #http://localhost:8091/?message=C:\OpenServer\domains\oms30.ru\OMS\Modules\InspectionModule\InspectionModule.php:743
    ide: 'http://localhost:8091/?message=%%f:%%l&/var/www/html/>C:/OpenServer/domains/symfony5/'
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
